<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit-no">

    <link rel="stylesheet" href="public/css/bootstrap.min.css">

    <title>Flores</title>
</head>
<body>
   <h1>As flores mais comuns e belas do mundo</h1>

    <div class="container">
        <?php foreach($especie as $flor) { ?>
            <h1><?php echo $especie['especie']; ?> </h1>
            <h4> <?php echo $descricao['descricao'] ?> </h4>
            <?php } ?>
    
</body>
</html>